services:
  flask-app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - AWS_REGION=${AWS_REGION}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - DYNAMODB_TABLE_NAME=${DYNAMODB_TABLE_NAME}
    volumes:
      - .:/app
    command: python app.py